name: "clang-format Check"
description: "Use clang-format to see if your C/C++/Protobuf code is formatted according to project guidelines."

branding:
  icon: "check-circle"
  color: "blue"

inputs:
  clang-format-version:
    description: 'The version of clang-format that you want to use.'
    required: false
    default: '13'
  check-path:
    description: 'The path to the directory you want to check for correct C/C++/Protobuf formatting. Default is the full repository.'
    required: false
    default: '.'
  exclude-regex:
    description: 'A regex to exclude files or directories that should not be checked. Default is empty.'
    required: false
    default: ''
  fallback-style:
    description: 'The fallback style for clang-format if no .clang-format file exists in your repository.'
    required: false
    default: 'llvm'

runs:
  using: "composite"
  steps:
    - name: Generate Dockerfile
      run: ${{ github.action_path }}/scripts/generateDockerfile.sh "${{ inputs.clang-format-version }}"
      shell: bash
    - name: Build Dockerfile
      run: ${{ github.action_path }}/scripts/buildDockerfile.sh
      shell: bash
    - name: Run Dockerfile
      run: ${{ github.action_path }}/scripts/runDockerfile.sh "/clang-format-action/workspace" "${{ inputs.check-path }}" "${{ inputs.fallback-style }}" "${{ inputs.exclude-regex }}"
      shell: bash
      env:
          ADDITIONAL_DOCKER_RUN_ARGS: "-v ${{ github.workspace }}:/clang-format-action/workspace"
